name: Test Github Actions
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Convert sample pdf to png
        uses: ./
        with:
          root_dir: ./sample
          match: "*.pdf"
      - name: Check output files
        run: |
          set -e
          pwd
          ls sample
          file sample/test.png |grep -q ' PNG '
